// 12-week badminton training roadmap content
// Phase 1: Foundation (Week 1-4), Phase 2: Development (Week 5-8), Phase 3: Game Ready (Week 9-12)

export const phases = [
    {
        id: 'foundation',
        name: 'Foundation',
        icon: '🌱',
        color: '#10B981',
        weeks: '1–4',
        desc: 'Nắm vững cầm vợt, tư thế, và các cú đánh cơ bản. Xây nền tảng vững chắc.',
    },
    {
        id: 'development',
        name: 'Development',
        icon: '🚀',
        color: '#3B82F6',
        weeks: '5–8',
        desc: 'Phát triển giao cầu, di chuyển, đánh lưới và smash nhẹ. Bắt đầu rally.',
    },
    {
        id: 'game-ready',
        name: 'Game Ready',
        icon: '🏆',
        color: '#F59E0B',
        weeks: '9–12',
        desc: 'Đánh đôi, chiến thuật cơ bản, và thi đấu tập. Sẵn sàng ra sân!',
    },
];

export const weeks = [
    // ===== PHASE 1: FOUNDATION =====
    {
        id: 1,
        phase: 'foundation',
        title: 'Làm quen với vợt & cầu',
        duration: '60 phút × 2 buổi',
        difficulty: 'Rất dễ',
        objectives: [
            'Biết cách cầm vợt forehand & backhand đúng cách',
            'Làm quen cảm giác vợt và cầu',
            'Đánh cầu tại chỗ (toss & hit)',
        ],
        drills: [
            {
                title: '🤝 Cầm vợt Forehand',
                time: '10 phút',
                desc: 'Cầm vợt như bắt tay – ngón cái đặt phẳng lên mặt rộng của grip. Không nắm quá chặt (lực nắm ~60%).',
                steps: [
                    'Giữ vợt đầu hướng lên trời, tay thuận nắm nhẹ grip',
                    'Ngón cái đặt phẳng lên mặt rộng phía sau grip',
                    'Các ngón còn lại ôm tự nhiên, có khoảng cách nhỏ giữa ngón trỏ và ngón giữa',
                    'Cổ tay thả lỏng – thử lắc nhẹ vợt để kiểm tra',
                ],
            },
            {
                title: '🤲 Cầm vợt Backhand',
                time: '10 phút',
                desc: 'Xoay vợt nhẹ, ngón cái đẩy lên mặt phẳng rộng phía sau – dùng lực ngón cái để đánh.',
                steps: [
                    'Từ tư thế forehand, xoay vợt nhẹ sang trái (nếu thuận tay phải)',
                    'Ngón cái đặt phẳng lên cạnh rộng phía sau grip',
                    'Khi đánh, dùng lực đẩy ngón cái thay vì quật cả tay',
                    'Luyện chuyển đổi forehand ↔ backhand nhiều lần',
                ],
            },
            {
                title: '🎯 Tung cầu & đánh tại chỗ',
                time: '20 phút',
                desc: 'Đứng tại chỗ, tự tung cầu lên và đánh forehand. Mục tiêu: cầu bay qua lưới.',
                steps: [
                    'Đứng cách lưới ~3m, chân rộng bằng vai',
                    'Tay không thuận cầm cầu, tung nhẹ lên trước mặt',
                    'Vợt đưa ra sau, quật nhẹ về phía trước đánh vào cầu',
                    'Không cần mạnh – tập trung vào điểm tiếp xúc đúng (giữa mặt vợt)',
                    'Lặp lại 30 lần, nghỉ 1 phút, rồi tiếp 30 lần nữa',
                ],
            },
            {
                title: '🏓 Rally nhẹ qua lưới',
                time: '15 phút',
                desc: 'Hai người đứng gần lưới (~3m mỗi bên), đánh qua lại nhẹ nhàng.',
                steps: [
                    'Đứng đối diện, mỗi bên cách lưới 2-3m',
                    'Đánh nhẹ nhàng, không cần mạnh',
                    'Mục tiêu: giữ cầu qua lại được 5 lần liên tục',
                    'Khi đạt 5 lần, tăng lên 10 lần',
                ],
            },
        ],
        tips: [
            { type: 'info', text: '💡 Không nắm vợt quá chặt! Cổ tay cần linh hoạt để đánh đúng kỹ thuật.' },
            { type: 'warning', text: '⚠️ Luôn khởi động 10 phút trước khi đánh (xem phần Khởi động & Giãn cơ).' },
        ],
        checklist: [
            'Đã tập cầm vợt forehand đúng cách',
            'Đã tập cầm vợt backhand đúng cách',
            'Đánh được cầu qua lưới khi tung tại chỗ',
            'Rally nhẹ qua lưới được ≥5 lần',
            'Giãn cơ sau buổi tập',
        ],
    },
    {
        id: 2,
        phase: 'foundation',
        title: 'Tư thế chuẩn bị & Forehand Clear',
        duration: '60 phút × 2 buổi',
        difficulty: 'Dễ',
        objectives: [
            'Nắm tư thế chuẩn bị (ready position) đúng cách',
            'Hiểu và tập cú forehand clear (đánh cao sâu)',
            'Bắt đầu cảm nhận nhịp đánh',
        ],
        drills: [
            {
                title: '🧍 Tư thế chuẩn bị (Ready Position)',
                time: '10 phút',
                desc: 'Tư thế sẵn sàng đón cầu – đây là vị trí bạn luôn quay về sau mỗi cú đánh.',
                steps: [
                    'Chân rộng hơn vai một chút, gối hơi khuỵu',
                    'Trọng tâm dồn vào phần trước bàn chân (nhón nhẹ)',
                    'Vợt giơ trước ngực, đầu vợt ngang tầm mắt',
                    'Mắt nhìn thẳng về phía đối thủ/lưới',
                    'Tập giữ tư thế này 30 giây, nghỉ, lặp lại 5 lần',
                ],
            },
            {
                title: '🎯 Forehand Clear – Đánh cao xa',
                time: '25 phút',
                desc: 'Cú đánh quan trọng nhất cho newbie! Đánh cầu bay cao và rơi sâu xuống cuối sân đối phương.',
                steps: [
                    'Đứng mặt bên (vai không thuận hướng lưới), chân thuận phía sau',
                    'Tay vợt đưa ra sau, khuỷu tay cao ngang vai',
                    'Mắt theo dõi cầu, chờ cầu rơi xuống vị trí trước trán',
                    'Quật vợt từ sau ra trước – tiếp xúc cầu ở điểm cao nhất',
                    'Sau khi đánh, vợt theo đà xuống bên trái cơ thể (nếu thuận phải)',
                    'Luyện: 1 người tung cầu cao, 1 người đánh clear. Đổi vai sau 15 quả',
                ],
            },
            {
                title: '🔄 Rally Clear',
                time: '20 phút',
                desc: 'Hai người đánh clear qua lại. Đứng ở giữa sân, đánh cầu bay cao rơi sâu.',
                steps: [
                    'Đứng ở giữa sân, cách lưới ~4m',
                    'Đánh clear qua lại – cầu phải bay cao và rơi gần đường biên cuối sân',
                    'Sau mỗi cú đánh, trở về tư thế chuẩn bị',
                    'Mục tiêu: rally 10 quả clear liên tục',
                ],
            },
        ],
        tips: [
            { type: 'info', text: '💡 Forehand clear dùng lực xoay thân + cổ tay, KHÔNG phải lực cánh tay. Hãy tưởng tượng bạn đang ném bóng xa!' },
            { type: 'success', text: '✅ Kiểm tra: Cầu clear tốt phải bay cao hơn đầu và rơi trong phạm vi 1m từ đường biên cuối sân.' },
        ],
        checklist: [
            'Giữ được tư thế chuẩn bị đúng cách',
            'Hiểu chuyển động forehand clear',
            'Đánh được clear qua lưới (cầu bay cao)',
            'Rally clear được ≥5 quả liên tục',
            'Luôn quay về tư thế chuẩn bị sau mỗi cú đánh',
        ],
    },
    {
        id: 3,
        phase: 'foundation',
        title: 'Backhand Clear & Drop Shot',
        duration: '60 phút × 2 buổi',
        difficulty: 'Dễ–Trung bình',
        objectives: [
            'Tập cú backhand clear',
            'Học cú drop shot (đánh rơi gần lưới)',
            'Phân biệt khi nào dùng clear vs drop',
        ],
        drills: [
            {
                title: '🔙 Backhand Clear',
                time: '20 phút',
                desc: 'Cú đánh bằng mặt sau vợt khi cầu bay về phía backhand (bên trái nếu thuận tay phải).',
                steps: [
                    'Đứng tư thế chuẩn bị, cầm backhand grip',
                    'Khi cầu bay về phía backhand, xoay lưng 3/4 về phía lưới',
                    'Khuỷu tay dẫn trước, vợt đưa ra sau',
                    'Dùng lực ngón cái đẩy + xoay cổ tay để đánh cầu',
                    'Tiếp xúc cầu ở điểm cao – đánh về phía sâu sân đối phương',
                    'Luyện: 1 người tung cầu về backhand, 1 người đánh. 15 quả rồi đổi',
                ],
            },
            {
                title: '🪶 Drop Shot – Đánh rơi',
                time: '20 phút',
                desc: 'Đánh cầu nhẹ qua lưới, rơi gần lưới phía sân đối phương. Dùng để thay đổi nhịp.',
                steps: [
                    'Tư thế giống clear (để đánh lừa đối phương)',
                    'Khi tiếp xúc cầu, giảm lực – chỉ dùng cổ tay nhẹ nhàng',
                    'Cầu bay vừa qua lưới và rơi nhanh',
                    'Drop tốt: cầu rơi cách lưới dưới 1m',
                    'Luyện xen kẽ: 3 quả clear → 1 quả drop. Đối tác phản hồi',
                ],
            },
            {
                title: '🔀 Phối hợp Clear–Drop',
                time: '15 phút',
                desc: 'Xen kẽ clear và drop không theo thứ tự, buộc đối tác phải đọc cú đánh.',
                steps: [
                    'Một người đánh xen kẽ clear/drop ngẫu nhiên',
                    'Người kia cố gắng đọc và trả cầu đúng',
                    'Mỗi hiệp 2 phút, rồi đổi vai',
                    'Chú ý: tư thế chuẩn bị của clear và drop phải GIỐNG NHAU',
                ],
            },
        ],
        tips: [
            { type: 'info', text: '💡 Bí quyết drop shot hiệu quả: tư thế chuẩn bị GIỐNG HỆT clear. Đối phương không biết bạn sẽ đánh gì!' },
            { type: 'warning', text: '⚠️ Backhand clear là cú khó – đừng nản nếu chưa đánh được xa. Tập dần từ gần rồi xa hơn.' },
        ],
        checklist: [
            'Nắm được cách cầm backhand grip',
            'Đánh được backhand clear (dù chưa xa)',
            'Đánh được drop shot qua lưới, rơi gần',
            'Phối hợp clear-drop xen kẽ được',
            'Phân biệt được khi nào dùng clear, khi nào dùng drop',
        ],
    },
    {
        id: 4,
        phase: 'foundation',
        title: 'Ôn tập & Mini Game',
        duration: '90 phút × 1 buổi',
        difficulty: 'Dễ',
        objectives: [
            'Ôn lại tất cả kỹ thuật tuần 1-3',
            'Chơi mini game để áp dụng',
            'Tự đánh giá tiến bộ',
        ],
        drills: [
            {
                title: '🔄 Ôn tập tổng hợp',
                time: '30 phút',
                desc: 'Lần lượt ôn lại các kỹ thuật đã học trong 3 tuần qua.',
                steps: [
                    '5 phút: Ôn cầm vợt forehand/backhand – chuyển đổi nhanh',
                    '5 phút: Tư thế chuẩn bị – kiểm tra lại form',
                    '10 phút: Rally forehand clear',
                    '5 phút: Backhand clear',
                    '5 phút: Drop shot',
                ],
            },
            {
                title: '🎮 Mini Game: King of the Court',
                time: '30 phút',
                desc: 'Chỉ dùng nửa sân. Mỗi người giao cầu 5 quả, ai thắng nhiều hơn được ở lại, thua thì đổi.',
                steps: [
                    'Chia đội hoặc xếp hàng. Chỉ dùng clear & drop (chưa cần smash)',
                    'Giao cầu bằng tay (chưa cần giao đúng luật)',
                    'Mỗi hiệp 5 quả, tính điểm đơn giản',
                    'Xoay vòng để mọi người đều được chơi',
                    'Mục tiêu: vui + áp dụng kỹ thuật thực tế',
                ],
            },
            {
                title: '📝 Tự đánh giá Phase 1',
                time: '10 phút',
                desc: 'Ngồi lại và tự đánh giá tiến bộ qua 4 tuần Foundation.',
                steps: [
                    'Cho điểm 1-5 mỗi kỹ thuật: cầm vợt, tư thế, clear, backhand, drop',
                    'Ghi chú điểm cần cải thiện',
                    'Trao đổi với bạn tập về điểm mạnh/yếu',
                    'Lập mục tiêu cho Phase 2',
                ],
            },
        ],
        tips: [
            { type: 'success', text: '🎉 Chúc mừng hoàn thành Phase 1! Bạn đã có nền tảng cơ bản. Phase 2 sẽ thú vị hơn!' },
            { type: 'info', text: '💡 Nếu thấy kỹ thuật nào chưa tốt, hoàn toàn OK! Tiếp tục ôn lại trong Phase 2.' },
        ],
        checklist: [
            'Ôn lại cầm vợt forehand/backhand',
            'Ôn lại tư thế chuẩn bị',
            'Rally clear ≥10 quả liên tục',
            'Chơi mini game áp dụng kỹ năng',
            'Hoàn thành tự đánh giá Phase 1',
        ],
    },

    // ===== PHASE 2: DEVELOPMENT =====
    {
        id: 5,
        phase: 'development',
        title: 'Giao cầu (Serve)',
        duration: '60 phút × 2 buổi',
        difficulty: 'Trung bình',
        objectives: [
            'Học giao cầu ngắn (short serve)',
            'Học giao cầu dài (long serve)',
            'Biết khi nào dùng giao dài vs giao ngắn',
        ],
        drills: [
            {
                title: '📐 Giao cầu ngắn (Short Serve)',
                time: '20 phút',
                desc: 'Giao cầu thấp sát lưới – kỹ thuật chính trong đánh đôi.',
                steps: [
                    'Đứng gần đường giao cầu, chân trước hướng lưới',
                    'Cầm cầu bằng tay trái ngang tầm eo',
                    'Vợt đặt phía sau, mặt vợt mở nhẹ hướng lên',
                    'Đẩy vợt nhẹ nhàng – cầu bay vừa qua lưới',
                    'Cầu tốt: bay sát lưới, rơi ngay sau đường giao cầu đối phương',
                    'Luyện: đặt hộp/chai nước ở vị trí đích, giao 20 quả nhắm vào đó',
                ],
            },
            {
                title: '🚀 Giao cầu dài (Long Serve)',
                time: '20 phút',
                desc: 'Giao cầu bay cao rơi sâu – dùng nhiều trong đánh đơn.',
                steps: [
                    'Đứng ở vị trí giao cầu, chân thuận phía sau',
                    'Thả cầu từ ngang tầm eo',
                    'Quật vợt mạnh từ dưới lên – cầu bay cao',
                    'Cầu tốt: bay cao, rơi trong khoảng 50cm từ đường biên cuối sân',
                    'Luyện: giao 20 quả, đếm bao nhiêu quả rơi đúng vùng',
                ],
            },
            {
                title: '🔀 Phối hợp giao cầu',
                time: '15 phút',
                desc: 'Giao xen kẽ ngắn/dài, đối tác tập đọc giao và trả cầu.',
                steps: [
                    'Giao 10 quả xen kẽ ngắn/dài ngẫu nhiên',
                    'Đối tác đứng ở vị trí nhận giao, tập trả cầu',
                    'Đổi vai sau 10 quả',
                    'Thảo luận: giao nào khó đọc hơn?',
                ],
            },
        ],
        tips: [
            { type: 'info', text: '💡 Giao cầu ngắn cần sự CHÍNH XÁC, giao cầu dài cần CHIỀU CAO. Cả hai đều quan trọng!' },
            { type: 'warning', text: '⚠️ Luật giao cầu: đầu vợt phải hướng xuống, chạm cầu dưới 1.15m tính từ mặt sân.' },
        ],
        checklist: [
            'Giao được cầu ngắn sát lưới',
            'Giao được cầu dài rơi sâu sân',
            'Phân biệt khi nào giao ngắn/giao dài',
            'Tập trả giao cầu của đối tác',
        ],
    },
    {
        id: 6,
        phase: 'development',
        title: 'Di chuyển chân (Footwork)',
        duration: '60 phút × 2 buổi',
        difficulty: 'Trung bình',
        objectives: [
            'Học bước chân cơ bản: bước tiến, bước lùi, bước ngang',
            'Hiểu cách di chuyển về 4 góc sân',
            'Phối hợp footwork với cú đánh',
        ],
        drills: [
            {
                title: '👣 Bước chân cơ bản',
                time: '15 phút',
                desc: 'Tập các loại bước chân mà không cần cầu – chỉ tập di chuyển.',
                steps: [
                    'Bước tiến: từ giữa sân → lưới (3 bước dồn)',
                    'Bước lùi: từ giữa sân → cuối sân (3 bước chéo)',
                    'Bước ngang: từ giữa → sang trái/phải (2 bước dồn)',
                    'Sau mỗi lần di chuyển, quay về giữa sân (tư thế chuẩn bị)',
                    'Tập mỗi hướng 10 lần, tốc độ vừa phải',
                ],
            },
            {
                title: '⭐ Shadow Footwork (4 góc)',
                time: '15 phút',
                desc: 'Di chuyển đến 4 góc sân theo thứ tự, không có cầu. Gọi là "shadow" vì tập hình bóng.',
                steps: [
                    'Đứng giữa sân, tư thế chuẩn bị',
                    'Di chuyển lần lượt: góc lưới phải → về giữa → góc lưới trái → về giữa → góc sau phải → về giữa → góc sau trái → về giữa',
                    'Mỗi góc, giả vờ đánh 1 cú (forehand ở góc phải, backhand ở góc trái)',
                    'Tập 5 vòng, nghỉ 1 phút giữa mỗi vòng',
                    'Lưu ý: LUÔN quay về giữa sân sau mỗi góc',
                ],
            },
            {
                title: '🏃‍♀️ Footwork + Đánh cầu',
                time: '20 phút',
                desc: 'Kết hợp di chuyển với đánh cầu thực tế.',
                steps: [
                    'Đối tác tung/đánh cầu vào các vị trí ngẫu nhiên',
                    'Di chuyển đến vị trí cầu, đánh trả, rồi về giữa sân',
                    'Bắt đầu chậm, tăng dần tốc độ',
                    'Mỗi hiệp 2 phút, nghỉ 1 phút, tổng 5 hiệp',
                ],
            },
        ],
        tips: [
            { type: 'info', text: '💡 Footwork là KỸ NĂNG QUAN TRỌNG NHẤT trong cầu lông! Đánh giỏi mà di chuyển kém = thua.' },
            { type: 'warning', text: '⚠️ Bạn nữ chú ý: di chuyển bằng bước dồn (shuffle), KHÔNG chạy bằng gót chân – dễ chấn thương đầu gối.' },
            { type: 'danger', text: '🚫 KHÔNG bao giờ nhảy bằng 1 chân rồi tiếp đất cùng chân đó – rất dễ quẹo/chấn thương.' },
        ],
        checklist: [
            'Tập bước tiến/lùi/ngang cơ bản',
            'Shadow footwork 4 góc sân',
            'Phối hợp được footwork + đánh cầu',
            'Luôn quay về giữa sân sau mỗi cú',
            'Giữ trọng tâm thấp khi di chuyển',
        ],
    },
    {
        id: 7,
        phase: 'development',
        title: 'Đánh lưới (Net Play)',
        duration: '60 phút × 2 buổi',
        difficulty: 'Trung bình',
        objectives: [
            'Học kỹ thuật net shot (bỏ nhỏ lưới)',
            'Học net kill (đập cầu ở lưới)',
            'Phối hợp net play trong rally',
        ],
        drills: [
            {
                title: '🕸️ Net Shot – Bỏ nhỏ lưới',
                time: '20 phút',
                desc: 'Đánh cầu nhẹ nhàng sát lưới, cầu vừa rơi qua bên kia. Cần sự tinh tế.',
                steps: [
                    'Đứng gần lưới, vợt giơ cao hơn lưới',
                    'Khi cầu đến gần, chỉ dùng ngón tay + cổ tay nhẹ nhàng đẩy cầu',
                    'Cầu chỉ cần vượt qua lưới rồi rơi ngay, càng sát lưới càng tốt',
                    'Tập forehand net: 15 quả. Backhand net: 15 quả',
                    'Hai người đứng gần lưới, bỏ nhỏ qua lại',
                ],
            },
            {
                title: '⚡ Net Kill – Đập lưới',
                time: '15 phút',
                desc: 'Khi cầu đối phương bỏ nhỏ nhưng hơi cao, đập thẳng xuống sân – cú đánh tấn công ở lưới.',
                steps: [
                    'Đối tác bỏ nhỏ cầu hơi cao (trên mép lưới)',
                    'Vợt giơ cao, đập nhanh xuống hướng sân đối phương',
                    'Không cần lực nhiều – nhanh và chính xác là đủ',
                    'Tập 15 quả, đổi vai',
                ],
            },
            {
                title: '🔄 Rally lưới',
                time: '20 phút',
                desc: 'Hai người đánh qua lại ở lưới, xen kẽ net shot và net kill.',
                steps: [
                    'Hai người đứng gần lưới (cách lưới ~1.5m)',
                    'Bỏ nhỏ qua lại – ai bỏ nhỏ cao thì đối phương được kill',
                    'Mục tiêu: rally net shot ≥10 quả không để cầu rơi',
                    'Game vui: ai để cầu rơi đầu tiên thua 1 điểm',
                ],
            },
        ],
        tips: [
            { type: 'info', text: '💡 Net shot tốt = tay nhẹ như lông vũ. Càng ít lực càng tốt – chỉ cần cầu vừa qua lưới.' },
            { type: 'success', text: '✅ Mẹo nhỏ: khi bỏ nhỏ lưới, mặt vợt hơi ngửa lên – cầu sẽ lăn qua lưới thay vì bay xa.' },
        ],
        checklist: [
            'Bỏ nhỏ lưới forehand được',
            'Bỏ nhỏ lưới backhand được',
            'Net kill khi cầu cao',
            'Rally lưới ≥10 quả',
            'Phân biệt khi nào bỏ nhỏ vs kill',
        ],
    },
    {
        id: 8,
        phase: 'development',
        title: 'Smash nhẹ & Ôn Phase 2',
        duration: '90 phút × 1 buổi',
        difficulty: 'Trung bình',
        objectives: [
            'Học cú smash cơ bản (đập cầu)',
            'Ôn tập toàn bộ Phase 2',
            'Mini game áp dụng đầy đủ kỹ thuật',
        ],
        drills: [
            {
                title: '💥 Smash cơ bản',
                time: '25 phút',
                desc: 'Cú đánh tấn công – đánh mạnh xuống sân đối phương. Cho newbie, tập smash nhẹ trước.',
                steps: [
                    'Tư thế giống forehand clear: mặt bên, tay đưa ra sau',
                    'Cầu phải ở VỊ TRÍ PHÍA TRƯỚC cơ thể (không phải phía sau)',
                    'Quật vợt mạnh, tiếp xúc cầu ở điểm CAO NHẤT có thể',
                    'Hướng mặt vợt xuống – cầu bay xuống sân đối phương',
                    'Bắt đầu với 50% lực, tăng dần khi đánh đúng điểm',
                    'Luyện: đối tác tung cầu cao, bạn smash. 20 quả rồi đổi',
                ],
            },
            {
                title: '🔄 Ôn tập Phase 2',
                time: '30 phút',
                desc: 'Ôn lại toàn bộ kỹ thuật Phase 2: giao cầu, footwork, net play, smash.',
                steps: [
                    '5 phút: Giao cầu ngắn + dài',
                    '5 phút: Shadow footwork 4 góc',
                    '10 phút: Rally lưới',
                    '10 phút: Rally có smash (clear → cầu cao → smash)',
                ],
            },
            {
                title: '🎮 Game thực tế (half-court)',
                time: '25 phút',
                desc: 'Chơi đánh đơn trên nửa sân, áp dụng tất cả kỹ thuật đã học.',
                steps: [
                    'Sử dụng nửa sân dọc (half-court singles)',
                    'Giao cầu đúng luật (ngắn hoặc dài)',
                    'Được dùng tất cả cú đánh: clear, drop, net, smash',
                    'Thi đấu 11 điểm mỗi hiệp',
                    'Xoay vòng để mọi người đều được đánh',
                ],
            },
        ],
        tips: [
            { type: 'warning', text: '⚠️ Smash KHÔNG cần dùng hết sức! 70% lực + đúng kỹ thuật > 100% lực mà sai form. Dễ chấn thương vai!' },
            { type: 'success', text: '🎉 Hoàn thành Phase 2! Bạn đã biết giao cầu, di chuyển, đánh lưới, và smash. Rất tuyệt!' },
        ],
        checklist: [
            'Smash được cầu xuống sân (dù chưa mạnh)',
            'Ôn lại giao cầu ngắn + dài',
            'Ôn lại footwork 4 góc',
            'Ôn lại net play',
            'Chơi game half-court áp dụng đủ kỹ thuật',
        ],
    },

    // ===== PHASE 3: GAME READY =====
    {
        id: 9,
        phase: 'game-ready',
        title: 'Nhận cầu & Phản xạ',
        duration: '60 phút × 2 buổi',
        difficulty: 'Trung bình',
        objectives: [
            'Cải thiện phản xạ nhận cầu',
            'Tập nhận smash (defense)',
            'Học cú lift (đẩy cầu từ lưới lên sâu sân)',
        ],
        drills: [
            {
                title: '🛡️ Nhận Smash (Defense)',
                time: '20 phút',
                desc: 'Tập đỡ cú smash – một trong những kỹ năng quan trọng nhất trong thực chiến.',
                steps: [
                    'Đứng giữa sân, tư thế phòng thủ: chân rộng, gối khuỵu sâu, vợt trước ngực',
                    'Đối tác smash nhẹ về phía bạn (50% lực)',
                    'Dùng backhand block – chỉ cần đưa vợt ra, cầu tự nảy lại',
                    'Không cần quật vợt – chỉ cần chắn đúng góc',
                    'Tập 15 quả phía forehand, 15 quả phía backhand',
                ],
            },
            {
                title: '🔝 Lift – Đẩy cầu lên',
                time: '15 phút',
                desc: 'Khi ở gần lưới, đẩy cầu bay cao về cuối sân đối phương – dùng khi bị áp sát lưới.',
                steps: [
                    'Đứng gần lưới, đối tác bỏ nhỏ cầu',
                    'Dưới lưới: dùng cổ tay đẩy cầu bay cao lên',
                    'Cầu phải bay đủ cao và sâu về cuối sân',
                    'Tập lift forehand 15 quả, backhand 15 quả',
                ],
            },
            {
                title: '⚡ Phản xạ nhanh (React Drill)',
                time: '20 phút',
                desc: 'Đối tác đánh cầu nhanh, liên tục về phía bạn. Tập phản xạ.',
                steps: [
                    'Đứng cách lưới ~3m, đối tác bên kia ~3m',
                    'Đánh cầu nhanh qua lại, drive ngang lưới',
                    'Không cần mạnh – cần NHANH và CHÍNH XÁC',
                    'Mỗi hiệp 1 phút, nghỉ 30 giây. Tổng 6 hiệp',
                ],
            },
        ],
        tips: [
            { type: 'info', text: '💡 Nhận smash: vợt để ở giữa cơ thể, chỉ cần xoay mặt vợt qua forehand/backhand. Không kịp thì ưu tiên backhand!' },
            { type: 'warning', text: '⚠️ Bài tập drive nhanh – hãy bắt đầu chậm rồi tăng tốc. Dễ bị đau cổ tay nếu đánh nhanh sai form.' },
        ],
        checklist: [
            'Đỡ được smash nhẹ bằng block',
            'Lift được cầu từ lưới lên sâu sân',
            'Phản xạ drive nhanh ≥10 quả liên tục',
            'Phân biệt defense forehand/backhand',
        ],
    },
    {
        id: 10,
        phase: 'game-ready',
        title: 'Đánh đôi (Doubles)',
        duration: '60 phút × 2 buổi',
        difficulty: 'Trung bình',
        objectives: [
            'Hiểu đội hình đánh đôi: trước-sau & hai bên',
            'Biết vai trò mỗi người trong đánh đôi',
            'Tập giao tiếp & phối hợp với đồng đội',
        ],
        drills: [
            {
                title: '📍 Đội hình tấn công: Trước-Sau',
                time: '15 phút',
                desc: 'Khi đội bạn đang tấn công (smash), đứng đội hình trước-sau.',
                steps: [
                    'Người sau: đứng giữa sân, phụ trách smash và clear',
                    'Người trước: đứng gần lưới, phụ trách intercept và net kill',
                    'Tập: người sau smash, người trước sẵn sàng kill nếu cầu trả lại lưới',
                    'Luân phiên vai trò sau 5 quả',
                ],
            },
            {
                title: '📍 Đội hình phòng thủ: Hai bên',
                time: '15 phút',
                desc: 'Khi đối phương tấn công, đứng đội hình hai bên (side by side).',
                steps: [
                    'Mỗi người phụ trách một nửa sân (trái/phải)',
                    'Đứng ngang nhau, khoảng giữa sân',
                    'Tập nhận smash: đối phương smash, 2 người phòng thủ đỡ',
                    'Ai gần cầu hơn thì đỡ – KHÔNG TRANH NHAU',
                ],
            },
            {
                title: '🎮 Đánh đôi thực tế',
                time: '25 phút',
                desc: 'Chơi đánh đôi, tập áp dụng đội hình tấn công và phòng thủ.',
                steps: [
                    'Chia 2 đội, chơi game 15 điểm',
                    'Tập chuyển đổi đội hình: tấn công → phòng thủ',
                    'Giao tiếp bằng lời: gọi "của anh/em!" khi đánh cầu',
                    'Sau game, thảo luận: phối hợp tốt gì, cần cải thiện gì',
                ],
            },
        ],
        tips: [
            { type: 'info', text: '💡 Đánh đôi = GIAO TIẾP. Luôn gọi "mình!", "em!", "anh!" khi đánh cầu. Im lặng = va chạm + mất điểm.' },
            { type: 'success', text: '✅ Quy tắc vàng: khi nghi ngờ cầu thuộc ai → người gần cầu hơn đánh. Luôn ưu tiên forehand.' },
        ],
        checklist: [
            'Hiểu đội hình trước-sau (tấn công)',
            'Hiểu đội hình hai bên (phòng thủ)',
            'Giao tiếp với đồng đội khi đánh',
            'Chơi game đôi áp dụng đội hình',
            'Chuyển đổi tấn công ↔ phòng thủ được',
        ],
    },
    {
        id: 11,
        phase: 'game-ready',
        title: 'Chiến thuật cơ bản',
        duration: '60 phút × 2 buổi',
        difficulty: 'Trung bình–Khá',
        objectives: [
            'Hiểu chiến thuật cơ bản trong đánh đơn và đánh đôi',
            'Tập đọc ý đồ đối phương',
            'Áp dụng chiến thuật trong game thực tế',
        ],
        drills: [
            {
                title: '🧠 Chiến thuật đánh đơn',
                time: '15 phút',
                desc: 'Học các nguyên tắc chiến thuật cơ bản để thắng điểm trong đánh đơn.',
                steps: [
                    'Nguyên tắc 1: Đẩy đối phương ra 4 góc sân, rồi đánh vào chỗ trống',
                    'Nguyên tắc 2: Xen kẽ clear (sâu) và drop (ngắn) – buộc đối phương chạy nhiều',
                    'Nguyên tắc 3: Chỉ smash khi cầu ở vị trí TỐT (trước mặt, đủ cao)',
                    'Nguyên tắc 4: Sau mỗi cú đánh, quay về giữa sân',
                    'Tập áp dụng: rally 20 quả, chủ ý xen kẽ clear-drop',
                ],
            },
            {
                title: '🧠 Chiến thuật đánh đôi',
                time: '15 phút',
                desc: 'Chiến thuật phối hợp với đồng đội trong đánh đôi.',
                steps: [
                    'Nguyên tắc 1: Giao cầu ngắn → người trước sẵn sàng kill',
                    'Nguyên tắc 2: Nếu bị đẩy ra sau → chuyển sang phòng thủ (hai bên)',
                    'Nguyên tắc 3: Người trước KHÔNG QUAY MẶT nhìn sau – tin tưởng đồng đội',
                    'Nguyên tắc 4: Đánh xuống = tấn công, đánh nâng = phòng thủ',
                    'Tập: chơi đôi 10 quả, phân tích sau mỗi rally',
                ],
            },
            {
                title: '👁️ Đọc cú đánh đối phương',
                time: '15 phút',
                desc: 'Học cách dự đoán đối phương sẽ đánh gì dựa vào tư thế và vị trí.',
                steps: [
                    'Quan sát: đối phương đưa vợt cao → có thể clear hoặc drop',
                    'Quan sát: đối phương ở gần lưới → có thể net shot hoặc lift',
                    'Quan sát: đối phương mặt vợt mở → cầu sẽ bay cao',
                    'Tập: rally 2 phút, sau đó mô tả bạn đọc được gì từ đối phương',
                ],
            },
        ],
        tips: [
            { type: 'info', text: '💡 Cầu lông là trò chơi CỜ VUA tốc độ cao. Nghĩ trước 1-2 cú: "mình đánh đây → đối phương sẽ trả đâu → mình sẽ đánh gì tiếp?"' },
            { type: 'success', text: '✅ Nhớ: đánh thông minh hơn đánh mạnh! Newbie thường thua vì cố smash liên tục. Hãy kiên nhẫn rally.' },
        ],
        checklist: [
            'Nắm 4 nguyên tắc chiến thuật đánh đơn',
            'Nắm 4 nguyên tắc chiến thuật đánh đôi',
            'Thử đọc ý đồ đối phương',
            'Áp dụng xen kẽ clear-drop trong rally',
            'Chơi game có áp dụng chiến thuật',
        ],
    },
    {
        id: 12,
        phase: 'game-ready',
        title: 'Thi đấu tập & Tổng kết',
        duration: '90 phút × 1 buổi',
        difficulty: 'Tất cả cấp độ',
        objectives: [
            'Thi đấu đơn & đôi áp dụng toàn bộ kỹ năng',
            'Tổng kết 12 tuần, đánh giá tiến bộ',
            'Lập kế hoạch luyện tập tiếp theo',
        ],
        drills: [
            {
                title: '🏆 Giải đấu nội bộ',
                time: '50 phút',
                desc: 'Tổ chức giải đấu nhỏ giữa các thành viên – vừa vui vừa áp dụng kỹ năng.',
                steps: [
                    'Chia thành các cặp đấu đôi (ưu tiên đôi vì nhóm có nữ)',
                    'Mỗi trận 15 điểm, đổi sân khi 1 bên đạt 8',
                    'Giao cầu đúng luật',
                    'Áp dụng tất cả kỹ thuật: clear, drop, smash, net, serve',
                    'Có trọng tài (người đang nghỉ) đếm điểm',
                ],
            },
            {
                title: '📊 Tổng kết 12 tuần',
                time: '20 phút',
                desc: 'Ngồi lại cùng nhóm, đánh giá tiến bộ và chia sẻ cảm nhận.',
                steps: [
                    'Mỗi người tự cho điểm 1-10 ở từng kỹ năng',
                    'So sánh với đánh giá tuần 4 – tiến bộ thế nào?',
                    'Chia sẻ: kỹ thuật nào thích nhất? Kỹ thuật nào khó nhất?',
                    'Thảo luận: muốn cải thiện gì trong tương lai?',
                ],
            },
            {
                title: '📝 Kế hoạch tiếp theo',
                time: '15 phút',
                desc: 'Lập kế hoạch luyện tập sau khi hoàn thành lộ trình cơ bản.',
                steps: [
                    'Lịch tập duy trì: 2 buổi/tuần, mỗi buổi 60-90 phút',
                    'Mỗi buổi: 10 phút khởi động → 20 phút ôn kỹ thuật → 30 phút game',
                    'Ghi chú cá nhân: điểm mạnh cần phát huy, điểm yếu cần ôn',
                    'Đặt mục tiêu 3 tháng tiếp theo',
                ],
            },
        ],
        tips: [
            { type: 'success', text: '🎉🏸 CHÚC MỪNG HOÀN THÀNH LỘ TRÌNH 12 TUẦN! Bạn đã từ newbie trở thành người chơi có nền tảng vững. Hãy tiếp tục tập luyện!' },
            { type: 'info', text: '💡 Cầu lông là môn thể thao cần thời gian. Hãy kiên nhẫn, tập đều đặn, và quan trọng nhất – VUI VẺ!' },
        ],
        checklist: [
            'Thi đấu đôi áp dụng chiến thuật',
            'Tự đánh giá tiến bộ so với tuần 4',
            'Chia sẻ cảm nhận với nhóm',
            'Lập kế hoạch luyện tập tiếp theo',
            'Đặt mục tiêu 3 tháng tiếp',
        ],
    },
];
